### ISSUE TITLE
Please remove personal contact info from the code entries.

### ISSUE THREAD

**Issue by vinnievg** [raspberrypilearning/sonic-pi-comp-finalists#3]
Hi
I've noticed that the entry space-in-your-ears.rb has a personal email address in it's header... might be polite to remove that from the public...
Regards
Graham

**Comment by MissPhilbin** [comment]
You mean space-symphony.rb? Fixed with thanks.

**Comment by LizUpton** [comment]
Aw! Beat me to it!

**Comment by vinnievg** [comment]
Good point - I pasted the wrong file name into the issue :-)

**Comment by MissPhilbin** [comment]
Hopefully @bennuttall and his super git skills can remove it from the history too.

**Comment by bennuttall** [comment]
History rewritten

https://github.com/raspberrypilearning/sonic-pi-comp-finalists/commits/master/code/space-symphony.rb

BOOM!
