### ISSUE TITLE
A Small Worry

### ISSUE THREAD

**Issue by vinnievg** [raspberrypilearning/sonic-pi-comp-finalists#4]
Hi,

I'm loving the variety and quality of all the finalists, haven't they done a brilliant job?

I noticed that 'one-small-step.rb' has a 25 second sample in it...

One of the children I worked with queried this when we showed them the ten finalists, as we'd interpreted the rules as saying we can't use samples not included with Sonic Pi.  This child wanted to use a sample and we'd said that it is against the competition rules.  I'm not really sure how to answer this with the child - so we thought we'd ask you.

Kindest Regards

Graham.

**Comment by MissPhilbin** [comment]
They are awesome. 

The sample you refer to is at the very end of the composition and was more of an addition than part of the song. In this case we disregarded it.

Carrie Anne.
